# Generated by Django 4.2.19 on 2025-02-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestfeedback',
            name='accompaniment_quality',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='address',
        ),
        migrations.AlterField(
            model_name='guestfeedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
